before_install:
  - sudo apt-get install -y libfreeimage3 libfreeimage-dev
  - sudo apt-get install -y python-opencv
  - gem install bundler -v 1.9.10
install:
  - bundle install
  - bundle exec rake compile
script: rspec