dist: bionic
addons:
  apt:
    packages:
      - libfreeimage3
      - libfreeimage-dev
      - libopencv-dev
before_install:
  - gem install bundler -v 1.9.10
install:
  - bundle install
  - bundle exec rake compile
script: rspec